import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import App from '../components/App';

const DATA = [
  { id: "todo-0", name: "Eat", completed: true },
  { id: "todo-1", name: "Code", completed: false },
  { id: "todo-2", name: "Sleep", completed: false },
  { id: "todo-3", name: "Repeat", completed: false }
];

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Todo List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <App tasks={DATA} />
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}

export default Home
